name: alr
channels: 
  - pytorch
  - anaconda
dependencies:
  - numpy>=1.21
  - scipy>=1.7
  - matplotlib
  - notebook
  - pandas>=1.3
  - seaborn
  - pytorch>=1.10
  - torchvision>=0.8
  - cudatoolkit=11.3
  - tqdm
  - pyyaml
  - joblib
  - plotly
  - pip
  - pip:
    - attrdict
    - wandb
