program: train_hpo.py

method: bayes

metric:
  name: Average_ctx_size over {median_tasks over {LMLHD per task} per ctx size} for context sizes (0, 1, 2, 5)
  goal: maximize

parameters:
  d_z:
    values: [1, 2, 4, 8, 16, 32]
  adam_lr:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.1
  n_hidden_units:
    values: [4, 8, 16, 32, 64]
  aggregator_type:
    value: "BA"
  loss_type: 
    value: "MC"
  input_mlp_std_y:
    value: ""
  self_attention_type:
    value: None
  f_act:
    value: "relu"
  n_hidden_layers:
    value: 2
  latent_prior_scale:
    value: 1.0
  decoder_output_scale:
    value: 0.1
  n_tasks_train: 
    value: 2**17
  validation_interval:
    value: 2**15
  device:
    value: "cuda"
  n_samples:
    value: 16
  n_context:
    value: [1, 32]
  seed:
    value: 1234
