# Experiment 1
name: "SLURM"   # MUST BE "SLURM"
partition: "single"  # "single" for cpu, "gpu_4" or gpu_8" for gpu
job-name: "Eval_neural_process" # this will be the experiment's name in slurm
num_parallel_jobs: 10 # max number of jobs executed in parallel
ntasks: 1   #  leave that like it is
cpus-per-task: 20   # there are 10 cores for each GPU
time: 1200   # in minutes

---
name: "Experimentaltry"
# Required: Can also be set in DEFAULT
path: "./log/sweepwork"   # location to save results in
repetitions: 100    # number of agents wandb should initialize

# if there should be multiple agents on one job, select a number > 1. Choose the same number for both options 'reps_per_job' and 'reps_in_parallel'
reps_per_job: 1
reps_in_parallel: 1
iterations: 1
params:
  aggregator_type: "BA"
  loss_type: "MC"
  input_mlp_std_y: ""
  self_attention_type: "None"
  f_act: "relu"
  n_hidden_layers: 2
  latent_prior_scale: 1.0
  decoder_output_scale: 0.1
  n_tasks_train: 2**17
  validation_interval: 2**15
  device: "cuda"
  n_samples: 16
  n_context: [1, 32]
  seed: 1234

benchmark_params:
  benchmark: "Quadratic1D"
  data_noise_std: 0.1
  n_task_meta: 256
  n_datapoints_per_task_meta: 64
  seed_task_meta: 1234
  seed_x_meta: 2234
  seed_noise_meta: 3234
  n_task_val: 16
  n_datapoints_per_task_val: 64
  seed_task_val: 1236
  seed_x_val: 2236
  seed_noise_val: 3236
  n_task_test: 256
  n_datapoints_per_task_test: 64
  seed_task_test: 1235
  seed_x_test: 2235
  seed_noise_test: 3235

wandb_sweep:
  name: "sweep_name"   # name of the newly created sweep
  metric:
    name: "objective"
    goal: "maximize"

  method: "bayes"

  parameters:
    d_z:
      values: [1, 2, 4, 8, 16, 32]
    adam_lr:
      distribution: log_uniform_values
      min: 0.00001
      max: 0.1
    n_hidden_units:
      values: [4, 8, 16, 32, 64]
    

wandb:
  sweep_id: "new"
  hp_combinations_per_agent: 2 # number of trials of hyperparameter combinations. After that the job will terminate
  project: "cw2-sweep"
  group: "test_group" # if key word is present, the runs will be grouped.


